stages:
  - test
  - bump
  - lint
  - security

include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  VERSION_FILE: "app/__version__.py"

# ---------- Bump Version (Fixed to Run Only Once) ----------
bump_version:
  stage: bump
  image: python:3.13
  rules:
    # Only run on direct pushes to main, NOT by the CI user
    - if: $CI_COMMIT_MESSAGE !~ /Bump version/ &&
        $CI_PIPELINE_SOURCE == "push" &&
        $CI_COMMIT_BRANCH == "main" &&
        $GITLAB_USER_LOGIN != "ci-bump-token" # Skip CI-triggered pipelines
  script:
    - pip install bump2version
    - git config --global user.name "GitLab CI Bump"
    - git config --global user.email "ci-bump@gitlab.com"
    - git remote set-url origin "https://ci-bump-token:${GITLAB_TOKEN}@gitlab.com/tahaomar001/fastapi-skilton.git"
    - >
      COMMIT_MSG="$(git log -1 --pretty=%B)" &&
      if echo "$COMMIT_MSG" | grep -q "#major"; then
        bump2version major $VERSION_FILE;
      elif echo "$COMMIT_MSG" | grep -q "#minor"; then
        bump2version minor $VERSION_FILE;
      else
        bump2version patch $VERSION_FILE;
      fi
    - git push origin HEAD:main
    - git push origin --tags

# ---------- Linting & Security (Run Once per Commit) ----------
lint_python:
  stage: lint
  image: python:3.13
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
  before_script:
    - pip install --upgrade pip
    - pip install bandit black codespell flake8 flake8-2020 flake8-bugbear flake8-comprehensions isort mypy pyupgrade
  script:
    - echo "Running flake8..."
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
    - echo "Running black..."
    - black --check .
    - echo "Running isort..."
    - isort --check-only --profile black .
    - echo "Running mypy..."
    - mkdir -p .mypy_cache
    - mypy --ignore-missing-imports --install-types --non-interactive .
    - echo "Running codespell..."
    - codespell .

custom_security_checks:
  stage: security
  image: python:3.13
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
  before_script:
    - pip install --upgrade pip
    - pip install bandit safety
  script:
    - echo "Running bandit..."
    - bandit --recursive --skip B101,B105 .
    - pip install --use-feature=fast-deps -r requirements.txt
    - safety check
